sudo: required
services:
  - docker

before_install:
  - docker build -t mrpjade/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true mrpjade/react-test npm test run

after_success:
  - docker build -t mrpjade/multi-client ./client
  - docker build -t mrpjade/multi-nginx ./nginx
  - docker build -t mrpjade/multi-server ./server
  - docker build -t mrpjade/multi-worker ./worker
  # Take those Images and push into Docker hub

  - echo $DOCKER_PWD | docker login

  - docker push mrpjade/multi-client
  - docker push mrpjade/multi-nginx
  - docker push mrpjade/multi-server
  - docker push mrpjade/multi-worker
